# Generated by Django 6.0.3 on 2026-04-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_pais_cliente_nacimiento_cliente_pais_origen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
    ]
